-f

diff --git a/pipebank b/pipebank
--- a/pipebank
+++ b/pipebank
@@ -59,6 +59,10 @@ elif [ "$1" == "get" ] || [ "$1" == "fetch" ]; then
         print_usage
         exit 1
     fi
+    if [ ! -f "$TEMP_PATH/$2" ]; then
+        echo "Error: invalid key"
+        exit 1
+    fi
     cat "$TEMP_PATH/$2"
     if [ "$1" == "fetch" ]; then
         rm "$TEMP_PATH/$2"
@@ -67,6 +71,10 @@ elif [ "$1" == "get" ] || [ "$1" == "fetch" ]; then
 elif [ "$1" == "delete" ] || [ "$1" == "rm" ]; then
     if [ $# -eq 1 ]; then
         print_usage
+        exit 1
+    fi
+    if [ ! -f "$TEMP_PATH/$2" ]; then
+        echo "Error: invalid key"
         exit 1
     fi
     rm "$TEMP_PATH/$2"
